# Pre-commit hooks for Cognitive Meeting Intelligence System
# Install: pre-commit install
# Run manually: pre-commit run --all-files

default_stages: [commit]
default_language_version:
  python: python3.11

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
      - id: debug-statements
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: ['--line-length=100']

  # Python imports sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']

  # Python linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.7.0
          - flake8-bugbear==23.5.9
        args: ['--max-line-length=100', '--extend-ignore=E203,W503,D100,D101,D102,D103,D104,D105,D106,D107']

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests==2.31.0.1
          - types-setuptools==67.8.0.0
        args: ['--ignore-missing-imports', '--python-version=3.11']
        files: ^src/
        pass_filenames: false

  # Security checks
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', 'src/', '-ll', '-i', '-x', 'tests/']
        files: ^src/

  # Markdown formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint
        args: ['--fix', '--disable', 'MD013', 'MD033', 'MD041']

  # YAML formatting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args: ['-c=.yamllint']

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.0 hadolint
        language: docker_image
        types: [dockerfile]

  # Commit message linting
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autoupdate_commit_msg: 'chore: update pre-commit hooks'