version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: cognitive_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  api:
    image: python:3.11-slim
    container_name: cognitive_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DATABASE_URL=sqlite:///./data/memories.db
    depends_on:
      - qdrant
    command: >
      bash -c "
        echo '📦 Installing dependencies...' &&
        pip install --quiet \
          fastapi==0.104.1 \
          uvicorn==0.24.0 \
          pydantic==2.6.4 \
          pydantic-settings==2.1.0 \
          aiosqlite==0.19.0 \
          numpy==1.26.4 \
          onnxruntime==1.17.3 \
          transformers==4.38.2 \
          qdrant-client==1.8.2 \
          vaderSentiment==3.3.2 \
          python-multipart \
          httpx &&
        echo '✅ Dependencies installed!' &&
        echo '🚀 Starting API at http://localhost:8000' &&
        echo '📚 Docs at http://localhost:8000/docs' &&
        python -m uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
      "