[tool.poetry]
name = "cognitive-meeting-ml"
version = "0.1.0"
description = "ML/data processing components for cognitive meeting intelligence"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
license = "MIT"
packages = [
    {include = "src/cognitive"},
    {include = "src/embedding"},
    {include = "src/extraction"},
    {include = "src/pipeline"},
    {include = "src/storage"},
    {include = "src/models"},
    {include = "src/utils"}
]

[tool.poetry.dependencies]
python = "^3.11"

# Core ML
numpy = "^1.26.4"
onnxruntime = "^1.17.3"
transformers = "^4.38.2"
scikit-learn = "^1.4.0"
sentence-transformers = "^2.2.2"

# Text analysis
vaderSentiment = "^3.3.2"
nltk = "^3.8.1"

# Database
aiosqlite = "^0.19.0"
sqlalchemy = "^2.0.25"

# Vector database
qdrant-client = "^1.8.2"

# Data processing
pydantic = "^2.11.7"

# Utilities
python-dotenv = "^1.0.0"
click = "^8.1.7"
rich = "^13.7.0"
loguru = "^0.7.2"

[tool.poetry.group.ml-convert]
optional = true

[tool.poetry.group.ml-convert.dependencies]
torch = "^2.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"