[tool.poetry]
name = "cognitive-meeting-api"
version = "0.1.0"
description = "API service for cognitive meeting intelligence system"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "src/api"}, {include = "src/models"}]

[tool.poetry.dependencies]
python = "^3.11"

# Web framework
fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.27.0"}
pydantic = "^2.11.7"
pydantic-settings = "^2.10.1"

# HTTP client
aiohttp = "^3.9.1"

# Database
aiosqlite = "^0.19.0"
sqlalchemy = "^2.0.25"

# Vector database client
qdrant-client = "^1.8.2"

# Basic ML for API operations
numpy = "^1.26.4"

# Utilities
python-dotenv = "^1.0.0"
loguru = "^0.7.2"

# Shared with ML component (would be a separate package in split)
cognitive-meeting-core = {path = "../cognitive-meeting-core", develop = true, optional = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"