name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Python Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update dependencies
      run: |
        # Create a requirements.in if it doesn't exist
        if [ ! -f requirements.in ]; then
          cp requirements.txt requirements.in
        fi
        
        # Update all dependencies to latest versions
        pip-compile --upgrade --resolver=backtracking requirements.in
        pip-compile --upgrade --resolver=backtracking requirements-dev.txt -o requirements-dev.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to Python dependencies.
          
          ### What changed
          - Updated `requirements.txt` with latest compatible versions
          - Updated `requirements-dev.txt` with latest development dependencies
          
          ### Testing checklist
          - [ ] All tests pass
          - [ ] No breaking changes identified
          - [ ] Application runs successfully
          
          ### Security
          Please review any security advisories for updated packages.
          
          ---
          *This PR was automatically generated by the dependency update workflow.*
        branch: automated-dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated

  update-pre-commit:
    name: Update Pre-commit Hooks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Update pre-commit hooks
      run: |
        python -m pip install --upgrade pip pre-commit
        pre-commit autoupdate

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update pre-commit hooks'
        title: 'chore: automated pre-commit hook updates'
        body: |
          ## Automated Pre-commit Hook Updates
          
          This PR contains automated updates to pre-commit hooks.
          
          ### What changed
          Updated all pre-commit hooks to their latest versions.
          
          ### Testing checklist
          - [ ] Pre-commit hooks run successfully
          - [ ] No new linting errors introduced
          
          ---
          *This PR was automatically generated by the dependency update workflow.*
        branch: automated-pre-commit-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          pre-commit